### PR TITLE
Feat/hostname support

### PR DESCRIPTION
**Pull request by hurali97**
## Motivation:

I was trying to run the **packages/e2e-example**, filled in my `bundleId` and I was getting the following error:

Screenshot 2022-09-01 at 9 14 27 PM

As I haven't worked with WebDriver, I looked up internet and It turned out that the **Mac** requires the `hostname` to be set to `0.0.0.0`. After setting this to the client creation block in [AppiumDriver.ts](https://github.com/bamlab/android-performance-profiler/blob/dd7bd687ea10bfc3bd70364f0650e360032079f3/packages/appium-helper/AppiumDriver.ts#L64), the test runs fine and everything is good.

I haven't updated the **packages/e2e-example/appium.test.ts** in the commits, as this hostName is optional and will fallback to `localhost` when not passed. Below is the code snippet on how we would want to use the changes being shipped with this PR (Docs updated):

```
  const driver = await AppiumDriver.create({
    appPackage: bundleId,
    appActivity: `${bundleId}.MainActivity`,
    hostName: '0.0.0.0'
  });
```

Edit:

```
  const driver = await AppiumDriver.create({
    appPackage: bundleId,
    appActivity: `${bundleId}.MainActivity`,
    remoteServerOptions: {
      hostName: '0.0.0.0'
    }
  });
```

### CODE REVIEW

**Comment by Almouro** [comment]
Hi @hurali97, thanks for submitting a PR for this!

Do you have a link to the issue where you found out `0.0.0.0` was needed?
Weirdly, we're all using macOS at BAM and never had to do this 🤔

It makes a lot of sense to be able to customize the server parameters though, but I think it'd be best to put this in a `remoteServerOptions` field so that it's not on the same level as the other capabilities

So that we could do:

```
const driver = await AppiumDriver.create({
    appPackage: bundleId,
    appActivity: `${bundleId}.MainActivity`,
    remoteServerOptions: {
      hostName: '0.0.0.0'
    }
  });
```

What do you think?

**Comment by hurali97** [comment]
> 

Hi @Almouro ,

That `remoteServerOptions` seems legit. And just to be on the same page, for now this options object will expect the hostName only. We can always extend that to match the needs in the future. I will totally update the implementation really soon.

Regarding that where I found out about `0.0.0.0`, below are the links:

https://github.com/appium/appium/issues/704#issuecomment-18917323
https://discuss.appium.io/t/how-do-i-fix-0-0-0-0-4723-on-appium-server/12846/11

**Comment by Almouro** [comment]
Wow that was fast thanks! Yeah I think that's a good start, we can extend them if needed later on 👌

I'm still confused by when we need to use `0.0.0.0` or `127.0.0.1` though. 😅

But it sounds like `0.0.0.0` should work for everyone, so I'd rather make it the default value in `AppiumDriver.ts` so people don't have to pass it (but can override it if need be)
Just to make usage as simple as possible for most people, so they don't have to pass an extra option. What do you think?

**Comment by hurali97** [comment]
> That was fast thanks! Yeah I think that's a good start, we can extend them if needed later on 👌
> 
> I'm still confused by when we need to use `0.0.0.0` or `127.0.0.1` though. 😅
> 
> But it sounds like `0.0.0.0` should work for everyone, so I'd rather make it the default value in `AppiumDriver.ts` so people don't have to pass it (but can override it if need be) Just to make usage as simple as possible for most people, so they don't have to pass an extra option. What do you think?

Yeah I totally agree. So something like this would suffice in `AppiumDriver.ts`:

```
    const client = await webdriver.remote({
      path: "/wd/hub",
      port: 4723,
      logLevel: "warn",
      capabilities,
      hostname: remoteServerOptions?.hostName ?? '0.0.0.0.0',
    });
```

@Almouro What do you say?

**Comment by Almouro** [comment]
@hurali97 yes perfect 👌

**Comment by Almouro** [comment]
@hurali97 seems all good for me, thanks! 🥳

Could you rebase on `main`? 🙏 CI is failing because of the conflict in `packages/appium-helper/package.json`

**Comment by Almouro** [comment]
Hey @hurali97, I had to add a few fixes to make the PR pass CI, hope you don't mind!
but it's ready to publish it now, thanks for your contribution! 🥳

**Pull request merged**
